---
output: 
  github_document: default
params:
   version: "1.4.756"
   #osx_version: "1.4.518"
   #win_version: "1.4.708"
knit: (function(input, ...) {
    rmarkdown::render(input); file.rename("download.md", "docs/_download.md")
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(plyr)
library(jsonlite)
library(urltools)
library(parsedate)
library(fs)

base_url <- "https://s3.amazonaws.com/rstudio-ide-build/desktop"

windows <- list(
   platform = "Windows 10/8/7",
   dir = "windows",
   file = "RStudio-%s.exe"
)

mac <- list(
   platform = "MacOS 10.13+",
   dir = "macos",
   file = "RStudio-%s.dmg"
)

ubuntu <- list(
   platform = "Ubuntu 18/Debian 10",
   dir = "bionic/amd64",
   file = "rstudio-%s-amd64.deb"
)

redhat <- list(
   platform = "Fedora 28/Red Hat 8",
   dir = "centos8/x86_64",
   file = "rstudio-%s-x86_64.rpm"
)

platforms <- list(windows, mac, ubuntu, redhat)

download_info <- lapply(platforms, function(platform) {
   version <- ifelse(platform$dir == "windows" && !is.null(params$win_version), params$win_version, params$version)
   version <- ifelse(platform$dir == "macos" && !is.null(params$osx_version), params$osx_version, version)
   platform$file <- sprintf(platform$file, version)
   platform$url <- paste(base_url, platform$dir, platform$file, sep = "/")
   platform$link <- paste0(
      "<a href=\"", platform$url, "\">", 
      "<i class=\"fa fa-download\"></i> ", platform$file, 
      "</a>"
   )
   aws_md5_url <- paste0(
      "https://eb7fgjmu47.execute-api.us-east-1.amazonaws.com/prod/md5?url=",
      urltools::url_encode(platform$url)
   )
   md5_info <- jsonlite::fromJSON(aws_md5_url)
   date <- parse_date(md5_info$last_modified)
   md5_info$date <- format.Date(date, format = "%m/%d/%y %H:%M %Z")
   md5_info$sha256_link <-  paste0(
      "<span class=\"sha256\" data-sha256=\"", md5_info$sha256, "\">", 
         paste0(substr(md5_info$sha256, 1, 8), "..."),
      "</span>"
   )
   md5_info$size <- fs::as_fs_bytes(md5_info$size)
   c(platform, md5_info) 
})

downloads <- ldply(download_info, data.frame, stringsAsFactors = FALSE)

knitr::kable(
   downloads[,c("platform", "link", "size", "sha256_link")], 
   col.names = c("Platform", "Download", "Size", "SHA-256"),
   align = c('l', 'l', 'l', 'l')
)
```
