<!-- html comment -->

## Headings

Headings have *id*, *class*, and *key:value* attributes.

```{=html}
<style>
.foobar {fdddd
  text-decoration: underline;
}
</style>
```
<div>

asfasdfasdfasdfsdfasfskkkkkkddddd

<div>

lddddasfNested div

::: {.foobarwina}
More [nestingdddddd](https://www.google.com)asdfsdfsdafsdafds
:::

</div>

</div>

## Code Blocks

## New Heading {.crush}

asdfasdfasdf

## Raw Content

### mkraw block.

Raw blocks have their \\content and a single *format* attibute.

Different border for raw blocks? (markup border perhaps?)

This block add an openxml (msword) break to the [document](https://www.google.com).

### raw inline

Raw inlines have their content and a single *format* attibute.

This text has raw asciidoc content: .

### html block

This block adds some styles to the document.

### html inlne

This text has some <a href="http://example.com">raw html</a> included inline.

## Blockquotes and Line Blocks

This is a blockquote:

> This is a block quote. This paragraph[^1] has two lines.
>
> 1.  This is a list inside a block quote.
> 2.  Second item.

## Div & Span

Divs and spans have *id*, *class*, and *key:value* attributes

This text has some [special]{.critical} formatting applied via a span.

term

:   

<!-- -->

``` {.python}
```

This is a line block (it preserves whitespace, often used for verse):

| The limerick packs laughs `anatomical`
| In space that is quite economical.
|    But the good ones I've seen
|    So seldom are clean
| And the clean ones so seldom are comical

## Tables

| Col1 | Col2 | Col3 |
|------|------|------|
|      |      |      |
|      |      |      |
|      |      |      |

::: {.illustration}
**Lorem Ipsum** is simply dummy text of the printing and [typesetting](https://www.google.com) industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not oasdfsd dsf

nly five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.

asdasdas

afasfasdfds
:::

::: {.illustration}
**Lorem Ipsum** is simply dummy text of the [rawnline] and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not oasdfsd dsfasdfasdf

nly five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.

asdasdas

afasfasdfds
:::

| Col1 | Col2 | Col3 |
|------|------|------|
|      |      |      |
|      |      |      |
|      |      |      |

::: {.illustration}
**Lorem Ipsum** is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not oasdfsd dsf

nly five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.

asdasdas

afasfasdfds
:::

[^1]: ::: {\#foo} :::
